# Copyright (C) 2026 Ben Weis <ben@springbird.app>
# Based on Lead, copyright (C) 2026 PlanetScale
#
# See LICENSE in the repository root for license terms.

[workspace]
resolver = "3"
members = ["boldi-vigna", "postgres", "segment", "tinql", "tokenizer"]

[workspace.package]
version = "0.4.0"
edition = "2024"
authors = ["PlanetScale", "Ben Weis <ben@springbird.app>"]
license = "AGPL-3.0-or-later"

[workspace.dependencies]
hashbrown = "0.16.1"
pest = "2"
pest_derive = "2"
regex-automata = "0.4"
regex-syntax = "0.8"
rustc-hash = "2.1.1"
thiserror = "2.0.18"

[profile.dev]
panic = "unwind"
split-debuginfo = "unpacked"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1
