-- Copyright (C) 2026 Ben Weis <ben@springbird.app>
-- Based on Lead, copyright (C) 2026 PlanetScale
--
-- See LICENSE in the repository root for license terms.

/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/am.rs:18
-- stannum::am::amhandler

    CREATE OR REPLACE FUNCTION @extschema@.amhandler(internal)
        RETURNS index_am_handler
        PARALLEL SAFE IMMUTABLE STRICT
        LANGUAGE c AS 'MODULE_PATHNAME', 'amhandler_wrapper';
    CREATE ACCESS METHOD stannum TYPE INDEX HANDLER @extschema@.amhandler;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/tool/capabilities.rs:21
-- stannum::tool::capabilities::capabilities
CREATE  FUNCTION "capabilities"() RETURNS jsonb /* JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'capabilities_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:280
-- stannum::score::full_score
CREATE  FUNCTION "full_score"(
	"ctid" tid /* pg_sys :: ItemPointerData */
) RETURNS real /* Option < f32 > */
IMMUTABLE STRICT PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'full_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:286
-- stannum::score::full_score
CREATE  FUNCTION "full_score"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"k1" real, /* Option < f32 > */
	"b" real /* Option < f32 > */
) RETURNS real /* Option < f32 > */
IMMUTABLE PARALLEL UNSAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'full_score_with_bm25_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:68
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT DEFAULT '<b>', /* & str */
	"end_tag" TEXT DEFAULT '</b>', /* & str */
	"query" TEXT DEFAULT NULL /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:99
-- stannum::highlight_udfs::highlight_ansi
CREATE  FUNCTION "highlight_ansi"(
	"text" TEXT, /* Option < & str > */
	"wrap_to" INT DEFAULT NULL, /* Option < i32 > */
	"query" TEXT DEFAULT NULL /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_ansi_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:188
-- stannum::highlight_udfs::highlight_support
CREATE  FUNCTION "highlight_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:264
-- stannum::storage::wal::index_reads_allowed
CREATE  FUNCTION "index_reads_allowed"(
	"index" regclass /* pgrx :: PgRelation */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'index_reads_allowed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:60
-- indexed_query
CREATE TYPE indexed_query;

-- postgres/src/operator.rs:60
-- stannum::operator::indexed_query_in
CREATE  FUNCTION "indexed_query_in"(
	"input" cstring /* Option < & :: core :: ffi :: CStr > */
) RETURNS indexed_query /* Option < indexed_query > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'indexed_query_in_wrapper';

-- postgres/src/operator.rs:60
-- stannum::operator::indexed_query_out
CREATE  FUNCTION "indexed_query_out"(
	"input" indexed_query /* indexed_query */
) RETURNS cstring /* :: pgrx :: ffi :: CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'indexed_query_out_wrapper';

-- postgres/src/operator.rs:60
-- indexed_query
CREATE TYPE indexed_query (
	INTERNALLENGTH = variable,
	INPUT = indexed_query_in, /* stannum::operator::indexed_query_in */
	OUTPUT = indexed_query_out, /* stannum::operator::indexed_query_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:108
-- stannum::highlight_udfs::highlight_ansi
CREATE  FUNCTION "highlight_ansi"(
	"text" TEXT, /* Option < & str > */
	"wrap_to" INT, /* Option < i32 > */
	"query" indexed_query /* indexed_query */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_ansi_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:228
-- stannum::operator::bind_query
CREATE  FUNCTION "bind_query"(
	"query" TEXT, /* & str */
	"index" oid /* pg_sys :: Oid */
) RETURNS indexed_query /* indexed_query */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:84
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT, /* & str */
	"end_tag" TEXT, /* & str */
	"query" indexed_query /* indexed_query */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:283
-- requires:
--   highlight
--   highlight_ansi
--   highlight_bound
--   highlight_ansi_bound
--   highlight_support


ALTER FUNCTION @extschema@.highlight(pg_catalog.text, pg_catalog.text, pg_catalog.text, pg_catalog.text)
    SUPPORT @extschema@.highlight_support;
ALTER FUNCTION @extschema@.highlight_ansi(pg_catalog.text, pg_catalog.int4, pg_catalog.text)
    SUPPORT @extschema@.highlight_support;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:255
-- stannum::storage::wal::logs_removal_horizons
CREATE  FUNCTION "logs_removal_horizons"(
	"index" regclass /* pgrx :: PgRelation */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'logs_removal_horizons_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:309
-- stannum::score::max_score
CREATE  FUNCTION "max_score"(
	"ctid" tid /* pg_sys :: ItemPointerData */
) RETURNS real /* Option < f32 > */
IMMUTABLE STRICT PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'max_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:152
-- stannum::udfs::maybe_quote
CREATE  FUNCTION "maybe_quote"(
	"text" TEXT /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'maybe_quote_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:157
-- stannum::udfs::ql_parse
CREATE  FUNCTION "ql_parse"(
	"query" TEXT, /* Option < & str > */
	"surface" bool DEFAULT true, /* bool */
	"tokenizer" TEXT DEFAULT 'unicode', /* & str */
	"case_folding" TEXT DEFAULT 'fold', /* & str */
	"accent_folding" TEXT DEFAULT 'fold', /* & str */
	"long_tokens" TEXT DEFAULT 'split', /* & str */
	"max_token_bytes" INT DEFAULT 256, /* i32 */
	"graphemes" TEXT DEFAULT 'emoji', /* & str */
	"position_gaps" TEXT DEFAULT 'preserve' /* & str */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ql_parse_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:296
-- stannum::score::score
CREATE  FUNCTION "score"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"dense_ratio" real DEFAULT 0.10, /* Option < f32 > */
	"k1" real DEFAULT NULL, /* Option < f32 > */
	"b" real DEFAULT NULL, /* Option < f32 > */
	"term_add" TEXT[] DEFAULT NULL, /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] DEFAULT NULL /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* Option < f32 > */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:319
-- stannum::score::score_bound
CREATE  FUNCTION "score_bound"(
	"document" TEXT, /* & str */
	"query" TEXT, /* & str */
	"heap_oid" INT, /* i32 */
	"index_oid" INT, /* i32 */
	"mode" INT, /* i32 */
	"dense_ratio" real, /* Option < f32 > */
	"k1" real, /* Option < f32 > */
	"b" real, /* Option < f32 > */
	"term_add" TEXT[], /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* f32 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:368
-- stannum::score::score_bound_indexed
CREATE  FUNCTION "score_bound_indexed"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"query" TEXT, /* & str */
	"heap_oid" INT, /* i32 */
	"index_oid" INT, /* i32 */
	"mode" INT, /* i32 */
	"dense_ratio" real, /* Option < f32 > */
	"k1" real, /* Option < f32 > */
	"b" real, /* Option < f32 > */
	"term_add" TEXT[], /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* f32 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_bound_indexed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:5245
-- stannum::score::score_inspect
CREATE  FUNCTION "score_inspect"(
	"index" regclass, /* Option < PgRelation > */
	"query" TEXT, /* Option < & str > */
	"dense_ratio" real DEFAULT 0.10, /* Option < f32 > */
	"term_add" TEXT[] DEFAULT NULL, /* :: std :: option :: Option < Vec < Option < String > > > */
	"term_replace" TEXT[] DEFAULT NULL /* :: std :: option :: Option < Vec < Option < String > > > */
) RETURNS TABLE (
	"term" TEXT,  /* String */
	"weight" real  /* f32 */
)
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_inspect_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:5572
-- stannum::score::score_support
CREATE  FUNCTION "score_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:5863
-- requires:
--   full_score
--   full_score_with_bm25
--   score
--   max_score
--   score_bound
--   score_bound_indexed
--   score_support


ALTER FUNCTION @extschema@.full_score(pg_catalog.tid) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.full_score(pg_catalog.tid, pg_catalog.float4, pg_catalog.float4) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.score(pg_catalog.tid, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.max_score(pg_catalog.tid) SUPPORT @extschema@.score_support;
REVOKE ALL ON FUNCTION @extschema@.score_bound(pg_catalog.text, pg_catalog.text, pg_catalog.int4, pg_catalog.int4, pg_catalog.int4, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION @extschema@.score_bound_indexed(pg_catalog.tid, pg_catalog.text, pg_catalog.int4, pg_catalog.int4, pg_catalog.int4, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/tool/search.rs:13
-- stannum::tool::search::search
CREATE  FUNCTION "search"(
	"index" regclass, /* PgRelation */
	"query" TEXT, /* Option < & str > */
	"limit" INT DEFAULT 10, /* i32 */
	"snippet" TEXT DEFAULT 'html', /* & str */
	"begin_tag" TEXT DEFAULT '<mark>', /* & str */
	"end_tag" TEXT DEFAULT '</mark>', /* & str */
	"k1" real DEFAULT NULL, /* Option < f32 > */
	"b" real DEFAULT NULL /* Option < f32 > */
) RETURNS TABLE (
	"ctid" tid,  /* pg_sys :: ItemPointerData */
	"score" real,  /* f32 */
	"snippet" TEXT  /* Option < String > */
)
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'search_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/tool/search.rs:38
-- stannum::tool::search::search_count
CREATE  FUNCTION "search_count"(
	"index" regclass, /* PgRelation */
	"query" TEXT /* Option < & str > */
) RETURNS bigint /* i64 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'search_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:247
-- stannum::udfs::segment_info
CREATE  FUNCTION "segment_info"(
	"index" regclass /* PgRelation */
) RETURNS TABLE (
	"ordinal" bigint,  /* i64 */
	"kind" TEXT,  /* String */
	"root_block" bigint,  /* i64 */
	"docs" bigint,  /* i64 */
	"dead_docs" bigint,  /* i64 */
	"sum_doc_lengths" bigint,  /* i64 */
	"total_pages" bigint,  /* i64 */
	"generation" bigint  /* i64 */
)
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'segment_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:210
-- stannum::operator::stannum_text_cmpfunc
CREATE  FUNCTION "stannum_text_cmpfunc"(
	"document" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:216
-- stannum::operator::stannum_text_cmpfunc_indexed
CREATE  FUNCTION "stannum_text_cmpfunc_indexed"(
	"document" TEXT, /* & str */
	"query" indexed_query /* indexed_query */
) RETURNS bool /* bool */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_indexed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:659
-- stannum::operator::stannum_text_cmpfunc_support
CREATE  FUNCTION "stannum_text_cmpfunc_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/selectivity.rs:145
-- stannum::selectivity::stannum_text_restrict

    CREATE OR REPLACE FUNCTION @extschema@.stannum_text_restrict(internal, oid, internal, integer)
        RETURNS float8
        PARALLEL SAFE STRICT
        LANGUAGE c AS 'MODULE_PATHNAME', 'stannum_text_restrict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:911
-- requires:
--   amhandler
--   indexed_query
--   stannum_text_cmpfunc
--   stannum_text_cmpfunc_indexed
--   stannum_text_cmpfunc_support
--   bind_query
--   stannum_text_restrict


CREATE OPERATOR pg_catalog.==> (
    PROCEDURE = @extschema@.stannum_text_cmpfunc,
    LEFTARG = pg_catalog.text,
    RIGHTARG = pg_catalog.text,
    RESTRICT = @extschema@.stannum_text_restrict
);

CREATE OPERATOR pg_catalog.==> (
    PROCEDURE = @extschema@.stannum_text_cmpfunc_indexed,
    LEFTARG = pg_catalog.text,
    RIGHTARG = @extschema@.indexed_query,
    RESTRICT = @extschema@.stannum_text_restrict
);

CREATE OPERATOR CLASS @extschema@.stannum_text_ops DEFAULT FOR TYPE pg_catalog.text USING stannum AS
    OPERATOR 1 pg_catalog.==>(pg_catalog.text, pg_catalog.text),
    OPERATOR 2 pg_catalog.==>(pg_catalog.text, @extschema@.indexed_query),
    STORAGE pg_catalog.text;

ALTER FUNCTION @extschema@.stannum_text_cmpfunc(pg_catalog.text, pg_catalog.text)
    SUPPORT @extschema@.stannum_text_cmpfunc_support;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:120
-- stannum::udfs::tokenize
CREATE  FUNCTION "tokenize"(
	"text" TEXT, /* Option < & '_ str > */
	"tokenizer" TEXT DEFAULT 'unicode', /* & str */
	"case_folding" TEXT DEFAULT 'fold', /* & str */
	"accent_folding" TEXT DEFAULT 'fold', /* & str */
	"long_tokens" TEXT DEFAULT 'split', /* & str */
	"max_token_bytes" INT DEFAULT 256, /* i32 */
	"graphemes" TEXT DEFAULT 'emoji', /* & str */
	"position_gaps" TEXT DEFAULT 'preserve' /* & str */
) RETURNS SETOF TEXT /* String */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tokenize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:330
-- stannum::udfs::verify_index
CREATE  FUNCTION "verify_index"(
	"index" regclass, /* PgRelation */
	"heap_check" bool DEFAULT false /* bool */
) RETURNS TABLE (
	"severity" TEXT,  /* String */
	"location" TEXT,  /* String */
	"message" TEXT  /* String */
)
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'verify_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:381
-- stannum::udfs::version
CREATE  FUNCTION "version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:247
-- stannum::storage::wal::wal_rmgr_id
CREATE  FUNCTION "wal_rmgr_id"() RETURNS INT /* Option < i32 > */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'wal_rmgr_id_wrapper';
/* </end connected objects> */

