/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:285

CREATE TABLE @extschema@.jieba_words (
    word text PRIMARY KEY,
    freq integer NOT NULL DEFAULT 0 CHECK (freq >= 0),
    tag text
);
REVOKE ALL ON TABLE @extschema@.jieba_words FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/am.rs:18
-- stannum::am::amhandler

    CREATE OR REPLACE FUNCTION @extschema@.amhandler(internal)
        RETURNS index_am_handler
        PARALLEL SAFE IMMUTABLE STRICT
        LANGUAGE c AS 'MODULE_PATHNAME', 'amhandler_wrapper';
    CREATE ACCESS METHOD stannum TYPE INDEX HANDLER @extschema@.amhandler;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/stopwords.rs:60
-- stannum::stopwords::builtin_stop_words
CREATE  FUNCTION "builtin_stop_words"(
	"preset" TEXT /* & str */
) RETURNS SETOF TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'builtin_stop_words_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:198
-- stannum::score::full_score
CREATE  FUNCTION "full_score"(
	"ctid" tid /* pg_sys :: ItemPointerData */
) RETURNS real /* Option < f32 > */
IMMUTABLE STRICT PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'full_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:204
-- stannum::score::full_score
CREATE  FUNCTION "full_score"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"k1" real, /* Option < f32 > */
	"b" real /* Option < f32 > */
) RETURNS real /* Option < f32 > */
IMMUTABLE PARALLEL UNSAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'full_score_with_bm25_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:69
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT DEFAULT '<b>', /* & str */
	"end_tag" TEXT DEFAULT '</b>', /* & str */
	"query" TEXT DEFAULT NULL /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:92
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT, /* & str */
	"end_tag" TEXT, /* & str */
	"query" TEXT, /* Option < & str > */
	"field" TEXT /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_field_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:169
-- stannum::highlight_udfs::highlight_ansi
CREATE  FUNCTION "highlight_ansi"(
	"text" TEXT, /* Option < & str > */
	"wrap_to" INT DEFAULT NULL, /* Option < i32 > */
	"query" TEXT DEFAULT NULL /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_ansi_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:293
-- stannum::highlight_udfs::highlight_support
CREATE  FUNCTION "highlight_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:451
-- stannum::dict::index_analysis
CREATE  FUNCTION "index_analysis"(
	"index" regclass /* PgRelation */
) RETURNS TABLE (
	"index_name" TEXT,  /* String */
	"recorded_jieba_version" INT,  /* Option < i32 > */
	"recorded_dict_fingerprint" bigint,  /* Option < i64 > */
	"runtime_jieba_version" INT,  /* Option < i32 > */
	"runtime_dict_fingerprint" bigint,  /* Option < i64 > */
	"matches" bool,  /* Option < bool > */
	"status" TEXT  /* String */
)
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'index_analysis_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:264
-- stannum::storage::wal::index_reads_allowed
CREATE  FUNCTION "index_reads_allowed"(
	"index" regclass /* pgrx :: PgRelation */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'index_reads_allowed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:313
-- stannum::udfs::index_stats

    CREATE FUNCTION @extschema@.index_stats("index" regclass)
    RETURNS TABLE (documents bigint, dead_documents bigint, dead_ratio float8,
        segments int, immutable_segments int, mutable_segments int,
        next_generation bigint, total_pages bigint, dictionary_pages bigint,
        total_length bigint, average_length float8,
        analysis_matches bool, analysis_detail text)
    STRICT VOLATILE PARALLEL UNSAFE
    LANGUAGE c AS 'MODULE_PATHNAME', 'index_stats_wrapper';
    CREATE VIEW @extschema@.index_health WITH (security_invoker = true) AS
    SELECT c.oid::regclass AS index, s.* FROM pg_class c
    CROSS JOIN LATERAL @extschema@.index_stats(c.oid) s
    WHERE c.relkind = 'i' AND c.relam = (SELECT oid FROM pg_am WHERE amname = 'stannum');
    COMMENT ON COLUMN @extschema@.index_health.dictionary_pages IS 'Pages intersected by every immutable segment''s dictionary extents, whether or not this backend ever read them. EXPLAIN''s Dictionary Pages Read counts only the pages a given scan actually pinned; the two differ by design and agree only for a fully-scanned index.';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:61
-- indexed_query
CREATE TYPE indexed_query;

-- postgres/src/operator.rs:61
-- stannum::operator::indexed_query_in
CREATE  FUNCTION "indexed_query_in"(
	"input" cstring /* Option < & :: core :: ffi :: CStr > */
) RETURNS indexed_query /* Option < indexed_query > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'indexed_query_in_wrapper';

-- postgres/src/operator.rs:61
-- stannum::operator::indexed_query_out
CREATE  FUNCTION "indexed_query_out"(
	"input" indexed_query /* indexed_query */
) RETURNS cstring /* :: pgrx :: ffi :: CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'indexed_query_out_wrapper';

-- postgres/src/operator.rs:61
-- indexed_query
CREATE TYPE indexed_query (
	INTERNALLENGTH = variable,
	INPUT = indexed_query_in, /* stannum::operator::indexed_query_in */
	OUTPUT = indexed_query_out, /* stannum::operator::indexed_query_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:175
-- stannum::operator::bind_query
CREATE  FUNCTION "bind_query"(
	"query" TEXT, /* & str */
	"index" oid /* pg_sys :: Oid */
) RETURNS indexed_query /* indexed_query */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:137
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT, /* & str */
	"end_tag" TEXT, /* & str */
	"query" indexed_query, /* indexed_query */
	"field" TEXT /* Option < & str > */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_bound_field_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:178
-- stannum::highlight_udfs::highlight_ansi
CREATE  FUNCTION "highlight_ansi"(
	"text" TEXT, /* Option < & str > */
	"wrap_to" INT, /* Option < i32 > */
	"query" indexed_query /* indexed_query */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_ansi_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:110
-- stannum::highlight_udfs::highlight
CREATE  FUNCTION "highlight"(
	"text" TEXT, /* Option < & str > */
	"begin_tag" TEXT, /* & str */
	"end_tag" TEXT, /* & str */
	"query" indexed_query /* indexed_query */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'highlight_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/highlight_udfs.rs:395
-- requires:
--   highlight
--   highlight_ansi
--   highlight_bound
--   highlight_ansi_bound
--   highlight_support


ALTER FUNCTION @extschema@.highlight(pg_catalog.text, pg_catalog.text, pg_catalog.text, pg_catalog.text)
    SUPPORT @extschema@.highlight_support;
ALTER FUNCTION @extschema@.highlight_ansi(pg_catalog.text, pg_catalog.int4, pg_catalog.text)
    SUPPORT @extschema@.highlight_support;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:297
-- stannum::dict::jieba_add_word
CREATE  FUNCTION "jieba_add_word"(
	"word" TEXT, /* & str */
	"freq" INT DEFAULT 0, /* i32 */
	"tag" TEXT DEFAULT NULL /* Option < & str > */
) RETURNS void
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jieba_add_word_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:319
-- stannum::dict::jieba_delete_word
CREATE  FUNCTION "jieba_delete_word"(
	"word" TEXT /* & str */
) RETURNS void
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jieba_delete_word_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:338
-- stannum::dict::jieba_dict_version
CREATE  FUNCTION "jieba_dict_version"() RETURNS bigint /* i64 */
STRICT STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jieba_dict_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/dict.rs:342
-- stannum::dict::jieba_reload_dict
CREATE  FUNCTION "jieba_reload_dict"() RETURNS void
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jieba_reload_dict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:255
-- stannum::storage::wal::logs_removal_horizons
CREATE  FUNCTION "logs_removal_horizons"(
	"index" regclass /* pgrx :: PgRelation */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'logs_removal_horizons_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:227
-- stannum::score::max_score
CREATE  FUNCTION "max_score"(
	"ctid" tid /* pg_sys :: ItemPointerData */
) RETURNS real /* Option < f32 > */
IMMUTABLE STRICT PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'max_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:158
-- stannum::udfs::maybe_quote
CREATE  FUNCTION "maybe_quote"(
	"text" TEXT /* Option < & str > */
) RETURNS TEXT /* Option < String > */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'maybe_quote_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:163
-- stannum::udfs::ql_parse
CREATE  FUNCTION "ql_parse"(
	"query" TEXT, /* Option < & str > */
	"surface" bool DEFAULT true, /* bool */
	"tokenizer" TEXT DEFAULT 'unicode', /* & str */
	"case_folding" TEXT DEFAULT 'fold', /* & str */
	"accent_folding" TEXT DEFAULT 'fold', /* & str */
	"long_tokens" TEXT DEFAULT 'split', /* & str */
	"max_token_bytes" INT DEFAULT 256, /* i32 */
	"graphemes" TEXT DEFAULT 'emoji', /* & str */
	"position_gaps" TEXT DEFAULT 'preserve' /* & str */
) RETURNS TEXT /* Option < String > */
STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ql_parse_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:214
-- stannum::score::score
CREATE  FUNCTION "score"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"dense_ratio" real DEFAULT 0.10, /* Option < f32 > */
	"k1" real DEFAULT NULL, /* Option < f32 > */
	"b" real DEFAULT NULL, /* Option < f32 > */
	"term_add" TEXT[] DEFAULT NULL, /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] DEFAULT NULL /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* Option < f32 > */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:237
-- stannum::score::score_bound
CREATE  FUNCTION "score_bound"(
	"document" TEXT, /* & str */
	"query" TEXT, /* & str */
	"heap_oid" INT, /* i32 */
	"index_oid" INT, /* i32 */
	"mode" INT, /* i32 */
	"dense_ratio" real, /* Option < f32 > */
	"k1" real, /* Option < f32 > */
	"b" real, /* Option < f32 > */
	"term_add" TEXT[], /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* f32 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_bound_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:281
-- stannum::score::score_bound_indexed
CREATE  FUNCTION "score_bound_indexed"(
	"ctid" tid, /* pg_sys :: ItemPointerData */
	"query" TEXT, /* & str */
	"heap_oid" INT, /* i32 */
	"index_oid" INT, /* i32 */
	"mode" INT, /* i32 */
	"dense_ratio" real, /* Option < f32 > */
	"k1" real, /* Option < f32 > */
	"b" real, /* Option < f32 > */
	"term_add" TEXT[], /* :: std :: option :: Option < Vec < String > > */
	"term_replace" TEXT[] /* :: std :: option :: Option < Vec < String > > */
) RETURNS real /* f32 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_bound_indexed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:2815
-- stannum::score::score_inspect
CREATE  FUNCTION "score_inspect"(
	"index" regclass, /* Option < PgRelation > */
	"query" TEXT, /* Option < & str > */
	"dense_ratio" real DEFAULT 0.10, /* Option < f32 > */
	"term_add" TEXT[] DEFAULT NULL, /* :: std :: option :: Option < Vec < Option < String > > > */
	"term_replace" TEXT[] DEFAULT NULL /* :: std :: option :: Option < Vec < Option < String > > > */
) RETURNS TABLE (
	"term" TEXT,  /* String */
	"weight" real  /* f32 */
)
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_inspect_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:3170
-- stannum::score::score_support
CREATE  FUNCTION "score_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'score_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/score.rs:3433
-- requires:
--   full_score
--   full_score_with_bm25
--   score
--   max_score
--   score_bound
--   score_bound_indexed
--   score_support


ALTER FUNCTION @extschema@.full_score(pg_catalog.tid) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.full_score(pg_catalog.tid, pg_catalog.float4, pg_catalog.float4) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.score(pg_catalog.tid, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) SUPPORT @extschema@.score_support;
ALTER FUNCTION @extschema@.max_score(pg_catalog.tid) SUPPORT @extschema@.score_support;
REVOKE ALL ON FUNCTION @extschema@.score_bound(pg_catalog.text, pg_catalog.text, pg_catalog.int4, pg_catalog.int4, pg_catalog.int4, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION @extschema@.score_bound_indexed(pg_catalog.tid, pg_catalog.text, pg_catalog.int4, pg_catalog.int4, pg_catalog.int4, pg_catalog.float4, pg_catalog.float4, pg_catalog.float4, pg_catalog.text[], pg_catalog.text[]) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/search.rs:374
-- stannum::search::search
CREATE  FUNCTION "search"(
	"index" regclass, /* PgRelation */
	"query" TEXT, /* Option < & str > */
	"limit" INT DEFAULT 10, /* i32 */
	"snippet" TEXT DEFAULT 'html', /* & str */
	"begin_tag" TEXT DEFAULT '<mark>', /* & str */
	"end_tag" TEXT DEFAULT '</mark>', /* & str */
	"k1" real DEFAULT NULL, /* Option < f32 > */
	"b" real DEFAULT NULL /* Option < f32 > */
) RETURNS TABLE (
	"ctid" tid,  /* pg_sys :: ItemPointerData */
	"score" real,  /* f32 */
	"snippet" TEXT  /* Option < String > */
)
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'search_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/search.rs:429
-- stannum::search::search_count
CREATE  FUNCTION "search_count"(
	"index" regclass, /* PgRelation */
	"query" TEXT /* Option < & str > */
) RETURNS bigint /* i64 */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'search_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:272
-- stannum::udfs::segment_info
CREATE  FUNCTION "segment_info"(
	"index" regclass /* PgRelation */
) RETURNS TABLE (
	"ordinal" bigint,  /* i64 */
	"kind" TEXT,  /* String */
	"root_block" bigint,  /* i64 */
	"docs" bigint,  /* i64 */
	"dead_docs" bigint,  /* i64 */
	"sum_doc_lengths" bigint,  /* i64 */
	"total_pages" bigint,  /* i64 */
	"generation" bigint  /* i64 */
)
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'segment_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:153
-- stannum::operator::stannum_text_cmpfunc
CREATE  FUNCTION "stannum_text_cmpfunc"(
	"document" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:160
-- stannum::operator::stannum_text_cmpfunc_indexed
CREATE  FUNCTION "stannum_text_cmpfunc_indexed"(
	"document" TEXT, /* & str */
	"query" indexed_query /* indexed_query */
) RETURNS bool /* bool */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_indexed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:595
-- stannum::operator::stannum_text_cmpfunc_support
CREATE  FUNCTION "stannum_text_cmpfunc_support"(
	"request" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stannum_text_cmpfunc_support_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/selectivity.rs:144
-- stannum::selectivity::stannum_text_restrict

    CREATE OR REPLACE FUNCTION @extschema@.stannum_text_restrict(internal, oid, internal, integer)
        RETURNS float8
        PARALLEL SAFE STRICT
        LANGUAGE c AS 'MODULE_PATHNAME', 'stannum_text_restrict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/operator.rs:979
-- requires:
--   amhandler
--   indexed_query
--   stannum_text_cmpfunc
--   stannum_text_cmpfunc_indexed
--   stannum_text_cmpfunc_support
--   bind_query
--   stannum_text_restrict


CREATE OPERATOR pg_catalog.==> (
    PROCEDURE = @extschema@.stannum_text_cmpfunc,
    LEFTARG = pg_catalog.text,
    RIGHTARG = pg_catalog.text,
    RESTRICT = @extschema@.stannum_text_restrict
);

CREATE OPERATOR pg_catalog.==> (
    PROCEDURE = @extschema@.stannum_text_cmpfunc_indexed,
    LEFTARG = pg_catalog.text,
    RIGHTARG = @extschema@.indexed_query,
    RESTRICT = @extschema@.stannum_text_restrict
);

CREATE OPERATOR CLASS @extschema@.stannum_text_ops DEFAULT FOR TYPE pg_catalog.text USING stannum AS
    OPERATOR 1 pg_catalog.==>(pg_catalog.text, pg_catalog.text),
    OPERATOR 2 pg_catalog.==>(pg_catalog.text, @extschema@.indexed_query),
    STORAGE pg_catalog.text;

ALTER FUNCTION @extschema@.stannum_text_cmpfunc(pg_catalog.text, pg_catalog.text)
    SUPPORT @extschema@.stannum_text_cmpfunc_support;
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:126
-- stannum::udfs::tokenize
CREATE  FUNCTION "tokenize"(
	"text" TEXT, /* Option < & '_ str > */
	"tokenizer" TEXT DEFAULT 'unicode', /* & str */
	"case_folding" TEXT DEFAULT 'fold', /* & str */
	"accent_folding" TEXT DEFAULT 'fold', /* & str */
	"long_tokens" TEXT DEFAULT 'split', /* & str */
	"max_token_bytes" INT DEFAULT 256, /* i32 */
	"graphemes" TEXT DEFAULT 'emoji', /* & str */
	"position_gaps" TEXT DEFAULT 'preserve' /* & str */
) RETURNS SETOF TEXT /* String */
STABLE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tokenize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:445
-- stannum::udfs::verify_index
CREATE  FUNCTION "verify_index"(
	"index" regclass, /* PgRelation */
	"heap_check" bool DEFAULT false /* bool */
) RETURNS TABLE (
	"severity" TEXT,  /* String */
	"location" TEXT,  /* String */
	"message" TEXT  /* String */
)
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'verify_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/udfs.rs:496
-- stannum::udfs::version
CREATE  FUNCTION "version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- postgres/src/storage/wal.rs:247
-- stannum::storage::wal::wal_rmgr_id
CREATE  FUNCTION "wal_rmgr_id"() RETURNS INT /* Option < i32 > */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'wal_rmgr_id_wrapper';
/* </end connected objects> */

