# Copyright (C) 2026 Ben Weis <ben@springbird.app>
#
# See LICENSE in the repository root for license terms.

import json
from pathlib import Path
import unittest

from generate_tool_contract import (
    ROOT,
    build_manifest,
    classify_sql,
    generate,
    read,
    SQL_PATH,
    OPTIONS_PATH,
)


class GenerateToolContractTest(unittest.TestCase):
    def test_sql_parser_consumes_the_snapshot(self):
        sql = read(ROOT, SQL_PATH)
        catalog = classify_sql(sql, SQL_PATH)
        self.assertGreater(catalog["statements"], 0)
        self.assertEqual(len(catalog["functions"]), 41)
        self.assertIsNotNone(catalog["access_method"])
        self.assertTrue(any(function["support"] for function in catalog["functions"]))
        self.assertTrue(any(function["acl"] for function in catalog["functions"]))
        self.assertEqual(catalog["tables"][0]["name"], "jieba_words")
        self.assertEqual(catalog["views"][0]["options"]["security_invoker"], True)

    def test_manifest_is_derived_from_sources(self):
        manifest = build_manifest(ROOT)
        options = read(ROOT, OPTIONS_PATH)
        warning = next(
            option["tin_ignore_warning"]
            for option in manifest["reloptions"]
            if option["ignored"]
        )
        self.assertIn(warning, options)
        self.assertEqual(
            [option["name"] for option in manifest["reloptions"] if option["ignored"]],
            [
                "initial_segment_count",
                "target_segment_count",
                "max_mutable_segment_size",
                "max_merged_segment_size",
                "dead_percent_threshold",
            ],
        )
        self.assertEqual(len(manifest["reloptions"]), 16)
        self.assertEqual(len(manifest["gucs"]), 10)
        wal = next(guc for guc in manifest["gucs"] if guc["name"] == "stannum.wal_rmgr_id")
        self.assertEqual(wal["registered_when"], "shared_preload_libraries")
        self.assertEqual(wal["context"], "Postmaster")
        names = {function["name"] for function in manifest["functions"]}
        self.assertNotIn("capabilities", names)
        search = next(function for function in manifest["functions"] if function["name"] == "search")
        defaults = {argument["name"]: argument["default"] for argument in search["arguments"]}
        self.assertEqual(defaults["begin_tag"], "'<mark>'")
        self.assertEqual(defaults["end_tag"], "'</mark>'")

    def test_generate_is_idempotent(self):
        first_json, first_md = generate(ROOT)
        second_json, second_md = generate(ROOT)
        self.assertEqual(first_json, second_json)
        self.assertEqual(first_md, second_md)
        json.loads(first_json)
        self.assertTrue(first_md.startswith("<!-- Generated by tools/generate_tool_contract.py."))
        self.assertTrue(first_json.endswith("\n"))
        self.assertTrue(first_md.endswith("\n"))


if __name__ == "__main__":
    unittest.main()
