# Copyright (C) 2026 Ben Weis <ben@springbird.app>
# Based on Lead, copyright (C) 2026 PlanetScale
#
# See LICENSE in the repository root for license terms.

[package]
name = "stannum"
description = "Stannum: an experimental PostgreSQL search engine with TINQL and BM25 ranking"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["pg18"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17"]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18"]
pg_test = ["dep:serde_json"]

[dependencies]
pgrx = "=0.19.1"
siphasher = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
rustc-hash.workspace = true
thiserror.workspace = true
tokenizer = { path = "../tokenizer" }
tinql = { path = "../tinql" }
boldi-vigna = { path = "../boldi-vigna" }
segment = { path = "../segment" }

[dev-dependencies]
pgrx-tests = "=0.19.1"
